@startuml

!theme retro-coast from ../themes/retro-coast

hide <<Person>> stereotype
hide <<External Person>> stereotype


package "System Boundary with important title" as SystemBoundary <<important>> <<dashed>> <<System>> {

  person Person <<Person>> [
    == Person
    Person
  ]

  actor Actor <<Person>> [
    == Actor
    Actor
  ]

  component SoftwareSystem <<Software System>> [
    == Software System
    Software System
  ]

  component Container <<Container>> [
    == Container
    Container
  ]

  component Component <<dashed>> <<Component>> [
    == Component
    Component
  ]
}

together {
  package "Theme Colors" {
    component Primary <<primary>>
    component Secondary <<secondary>>
    component Tertiary <<tertiary>>
    component Quaternary <<quaternary>>
    component BgPrimary <<bgprimary>>
    component BgSecondary <<bgsecondary>>
    component BgTertiary <<bgtertiary>>
    component BgQuaternary <<bgquaternary>>
  }

  package Callouts <<Container>> {
    component Container1 <<note>> [
      == Container 1
      Container 1
    ]

    component Container2 <<warning>> [
      == Container 2
      Container 2
    ]

    component Container3 <<caution>> [
      == Container 3
      Container 3
    ]

    component Container4 <<important>> [
      == Container 4
      Container 4
    ]

    component Container5 <<tip>> [
      == Container 5
      Container 5
    ]

    component Container6 #back:white;line:00FFFF;text:green [
      == Custom Styles
      Container 6
    ]
    note top <<important>> {
      Some
      important
      note
    }
  }
}

package Relationships <<dotted>> {
  label " " as A
  label " " as B
  label " " as C
  label " " as D
  label " " as E
  label " " as F
  label " " as G
  label " " as H
  label " " as I
  label " " as J
  label " " as K
  label " " as L
}

A -d- B <<note>> : Note
C -d- D <<warning>> : Warning
E -d- F <<caution>> : Caution
G -d- H <<important>> : Important
I -d- J <<tip>> : Tip
K -d- L #line:green;text:f134f3 : Custom


SoftwareSystem .r.> Container <<highlight>> : says hello to
Container .r.> Component: says hello to


' Layout helper
SystemBoundary -d[hidden]- Callouts
Callouts -d[hidden]- Relationships
[Theme Colors] -d[hidden]- Relationships
[Theme Colors] -d[hidden]- Relationships
[Theme Colors] -d[hidden]- Relationships
[Theme Colors] -d[hidden]- Relationships


@enduml